# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

# Below is an example of intersphinx mapping declaration
# Add more mappings depending on what manual you want to link to
# Remove entirely if you don't need cross-linking

---
conf.py:
  copyright: 2015-2018
  project: Google reCAPTCHA v2.0
  version: 2.1.0
  release: 2.1.0
  extensions:
    - sphinx.ext.intersphinx
    - t3sphinx.ext.t3extras
    - t3sphinx.ext.t3tablerows
    - t3sphinx.ext.targets
    - sphinxcontrib.googlechart
    - sphinxcontrib.googlemaps
    - sphinxcontrib.slide
    - sphinxcontrib.youtube
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
  latex_documents:
  - - Index
    - jh_captcha.tex
    - reCAPTCHA v2.0
    - Jan Haffner
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
